# Generated by Django 5.2.5 on 2025-08-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_joined_date_player_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
