# Generated by Django 5.2.5 on 2025-08-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_address_player_age_player_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
